name: Automatic release main to release branches
on:
  push:
    branches:
      - main

jobs:
  nfa-release-shotgrid-config:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"

    - name: Fetch repository
      run: |
          git fetch --unshallow

    - name: Release main to s4
      run: |
          git checkout release/s4
          git pull
          git merge --no-ff main -m "Automatic merge main for release s4"
          git push

    - name: Release main to s3
      run: |
          git checkout release/s3
          git pull
          git merge --no-ff main -m "Automatic merge main for release s3"
          git push

    - name: Release main to s2
      run: |
          git checkout release/s2
          git pull
          git merge --no-ff main -m "Automatic merge main for release s2"
          git push