name: Github Actions Pull
on:
  pull_request:
    types: [closed]
jobs:
  update-4ejaars_source-branch:
   runs-on: ubuntu-latest
   steps:
    - run: echo "This job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "This job is running on a ${{ runner.os }} server."
    - run: echo "This job will update the 4ejaars_source branch."
    - uses: actions/checkout@v2
      with: 
        ref: 4ejaars_source
    - run: git config user.name github-actions
    - run: git config user.email github-actions@github.com
    - run: git config pull.rebase false
    - run: git fetch origin master
    - run: git merge -s recursive -X theirs master
    - run: git add .
    - run: git commit -m "Github Actions"
    - run: git push
  update-3ejaars_source-branch:
   runs-on: ubuntu-latest
   steps:
    - run: echo "This job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "This job is running on a ${{ runner.os }} server."
    - run: echo "This job will update the 3ejaars_source branch."
    - uses: actions/checkout@v2
      with: 
        ref: 3ejaars_source
    - run: git config user.name github-actions
    - run: git config user.email github-actions@github.com
    - run: git config pull.rebase false
    - run: git fetch origin master
    - run: git merge -s recursive -X theirs master
    - run: git add .
    - run: git commit -m "Github Actions"
    - run: git push