name: Github Actions Pull
on:
  pull_request:
    types: [closed]
jobs:
  update-s4-branch:
   runs-on: ubuntu-latest
   steps:
    - run: echo "This job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "This job is running on a ${{ runner.os }} server."
    - run: echo "This job will update the s4 branch."
    - uses: actions/checkout@v2
      with:
        ref: s4
    - run: git config user.name github-actions
    - run: git config user.email github-actions@github.com
    - run: git config pull.rebase false
    - run: git fetch origin master
    - run: git merge -s recursive -X theirs origin/master --allow-unrelated-histories
    - run: git add .
    - run: git status
    - run: git push
  update-s3-branch:
   runs-on: ubuntu-latest
   steps:
    - run: echo "This job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "This job is running on a ${{ runner.os }} server."
    - run: echo "This job will update the s3 branch."
    - uses: actions/checkout@v2
      with: 
        ref: s3
    - run: git config user.name github-actions
    - run: git config user.email github-actions@github.com
    - run: git config pull.rebase false
    - run: git fetch origin master
    - run: git merge -s recursive -X theirs origin/master --allow-unrelated-histories
    - run: git add .
    - run: git status
    - run: git push
  update-s2-branch:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is running on a ${{ runner.os }} server."
      - run: echo "This job will update the s2 branch."
      - uses: actions/checkout@v2
        with:
          ref: s2
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: git config pull.rebase false
      - run: git fetch origin master
      - run: git merge -s recursive -X theirs origin/master --allow-unrelated-histories
      - run: git add .
      - run: git status
      - run: git push